// compilation test for error assertion and
// error propagation

pub fn main() void = {
    noerror()!;
    error()!;
};

fn noerror() !unit = { };
fn catch() !unit = {
    error()?;
};
fn error() !unit = { => fail; };
